stages:
  - deps
  - build
  - deploy

default:
  image: php:7.3-apache

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2
  IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
  - node_modules/
  - vendor/

deps:php:
  stage: deps
  script:
    - php -v
    - ls -l
    - curl -sS https://getcomposer.org/installer | php --
    - php composer.phar install --no-interaction --no-dev --no-autoloader
    - php composer.phar dump-autoload --optimize
  artifacts:
    paths:
      - composer.phar
      - vendor/

deps:npm:
  image: node:12
  stage: deps
  script:
    - node -v
    - ls -l
    - npm install
    - npm run production
  artifacts:
    paths:
      - node_modules/
      - public/

build:
  stage: build
  script:
    - ls -l
  artifacts:
    paths:
      - vendor/
      - public/
      - bootstrap/
      - storage/framework #??? This will be overwritten by volume anyways, need to rethink this

docker:image:
  stage: deploy
  image: docker:19
  services:
    - docker:dind
  script:
    - docker info
    - docker build . --file docker/Dockerfile --tag $CI_REGISTRY_IMAGE:latest --tag $IMAGE_TAG
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker push $IMAGE_TAG
