language: php
php:
  - 7.4

env:
  global:
    - APP_ENV=staging
    - DOCKER_COMPOSE_VERSION=1.25.0
    - DOCKER_USERNAME=danmichaelo
    # GITHUB_TOKEN
    - secure: "IMeat6cXR6lMSuD3XcAnKnobi7EKg0DyAk/H9xG0f3pM+cswQcsnWbg6lsUIDuVQic7setN1mhj3a4ZumixlnkaJwWRn/5MD9p6pK+T5up5EnhapzHyDEbY1F06p+JVPwLTXv3ATXEC8HxR2fPlmwXUbAwMPz/Nfgzabg8b2uXkH7oI51rnn6yWcb66vatQzesALO5alAGae9GxYoeU77ymvpT8QBjRNH1BAb7NuYniG6i27UIhXOUg1O5LtllJsxnHLxBpr1xvFZZ63x5Bq8z3+ID9CREWjSMKjbVG07R8R2nIcf0pgyEasSZ8/Hzr037xvwk+xaGxT7VGTlpHwJEOBBKca1lo2CbbQwPfFpd8dcfOkTbV7toD9oVyo7Cl01fxmiZQTxfSa2n1pfBk/OVehmriqC1C5B6ceSERn4V6dEwNdDhmNmTjLwb9kVF5QH/2byyl9iEFsqXieZg4frdc/sMgC3BTCFic4Fst1H8F15xJyimo7U0NLgTee/pk1amcCIRWSuP/Podu5D8ietMAApdFwIeA3Y2YLIka395eL5dRRdDGQMnnCJbjnxhf2zZm8cFqHOWQe/9FvrQxDarDrRZdtyexUCnkX2PQX9LIuSoD69ldEzjipjdX0i3ngBvCu1MTeN6w+waNxyfiY4RiG9Mga6tPPcrm85JS6NB4="
    # SAUCE_USERNAME
    - secure: "ojG3a4e7U97Oel+y0MmTey6UR5f2+jyqoIfCvgNogeEVMmmPKmncF+bkXOP2VTCIQ0gaYey0Znz2e12BRO328IR56c6dm/EQu/oVgIb7JX57tJMp6T+A3GeZi0CuCSfOaMmnipcjM0PDxvsLRl5zmT2BwR/S658GPAY5o9fvkg7UspgMy+n1WHXo5sFpVo4ajKhs6H/cvSYXQvJuwc1uJO5NHeevGOf9pu3akT07IKywmMPYGgJXqwg0B89FQyOZv5GWrsm3SnSbH/Hd5Q2A6XsBbbluGsSuKQKCSu3AlgQCWAK19meUw/rdjoIAkKmoqpbeb2L86eFdtbmvp9ShJID5Fn6ieXbtkTm8o5RUIhPy66oFRl1hR7YaV7izzHJSMbdhedvOBhBf2rHBE8fzfGViSZYDFGenjfk0c1sHqX7WUAwfcmVnfKNuNMgLy+J+5yRu1fcG1eVIrNS7ESq/q72ksGjrlalNghjwRFNcR6CtmlzGdXo48cNzTTVwoJj/EqRIIu2vqiXpieh5Hjvdlle3PbDoHdFw6XiQStC/OCgfsXLPRLHQIpr/yRxGzi08FrDY3FZ9ckgmm5xnaO/ptyk9f6jGkXmRS0QaoOy3EYZKTxbxNYLQtTOmHhiLRlnPokJFrzNe30v7dXU6xcqdXt9Z8xAEcLDItdIDCH7SIYo="
    # SAUCE_ACCESS_KEY
    - secure: "jdMXMLl2GQG1Bfu8DP+r62k3C0NJsUwMGUTK+bwYWtbNrhYyTU9uS9h5hfPpnecobRkqEk0sxvd8D9+3IJNuTx3HJ6TVGu+JS4kK70HcWzAaXoJBxY/oO7Gjvus6qFVS6nRUydfVM1M+nPToMFdbQVzB1Xo8s12d5HkNuarKzwQs22n0lDHmvaycbVltPvTZpXhSkMv8ZnX1GWGNtpiDh+85HJtexvuR9DIBmBCymnLRbXk5Pkgx/EWDA5BiIqTlpQ/lvCwo8JvzHxQVwWTGGvJE7Dk4DmPe1mg2ljDYpH3/sMO6rXOceyTPNFH4Wq2KdGcpX+7WF9dUgCgdEmAn/wcs0GTNlFrTWhaFV8LZdz43sw2CeOrwv2G0cAGuYv29L2L7gz3O1i/+ga6ELuiueCeatU4NyCN++TEmMEomQ+PvegbaRketbg/v9Qt7gLZRanYprxUSTp2LnaxtltDxg2G8CS9aGhVdsdtfWAgvY5yIlwmyVXgtSrJ9iyO5nqmD4Fs3A6bS6YBCElD0QJZmwuqMWz6R94sPZUYvc3W6s82KneAdiKWH8bw/9gvodQkd6fNTOSFBBM0W5caQmSlHJ+vYRfZK5ztVO50cHxXMEAZxLnS8jsU6S2JIpJCd2DkgLBwcvN6ss+noO39x9TA6+p5K+OyVfHr2om+dBkW790U="
    # DOCKER_TOKEN
    - secure: "csbZBquwi4Thm4BmMCAn0prjPMtTk9lbK2bNLY12fuz0bOuKC0xS4D7UgJ4M14R3fUyrT7ae5bZziD6QjJiNJPy6lg2DLEzKsunOpCtQfUfhzXj+GrW/1c8Uc5PoJQyDZEPbjv++L328T1+axUl5dcNwH8ygJNW8ouCVLq/jwPoJGA3PP1NHoKOVRLYdXc96EBQE4ZM/rZUBJ4Ur3fAKtBNj4s22Zq8crVJbMTmFM2Ju5skST6ObL4Nb09INY0vmvkM2TBgRHadvdyX12pRylcWc05qeM3iqVSS05pmPkTQfx0Wah77xqDiYEjCTeFmCpXimYfzbzhA43kgB2ttCWLv/PB0rEDsDpFAaGLX3gJZKh1qMFlM0iqssGaZPwXjkRP9AqVz6CM8KZBLgHG+IN07XTgxLWzzes49yERb83hsMExsVImxskAgmCcwuCaJDgndoI5IrwVNsWdVOnh5DTOklyP/bHKX2y2H9PurfDDmyLHXWgjX69PlCFKYN4RNHVPWrpF57Mgox8vf5nFEPbtZ/lfSCmLQ78C5/FDcWWY2OBylb0/ngi9/mjtXcp9K3dkAiZbG0lUppfwA4R1cON2J4Oh6B8TozWksgskpKysrNMNRNCAqWGfXMhc6SfDyyQq2tTma9tJ/YwTaiB+cr6yJ/cx2pekfVBolzDC/M4K4="
addons:
  sauce_connect: true
  apt:
    packages:
      - docker-ce

services:
  docker

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - echo "$DOCKER_TOKEN" | docker login -u "$DOCKER_USERNAME" --password-stdin registry.example.com
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - nvm install lts/erbium
  - nvm use lts/erbium
  - docker --version
  - docker-compose --version
  - php --version
  - node --version

install:
  - ./dev.sh up -d

before_script:
  - ./dev.sh ps
  - ./dev.sh logs
  - curl --fail http://localhost:8081/

script:
  - ./vendor/bin/phplint ./ --exclude=vendor --exclude=node_modules
  - SAUCE_TUNNEL=$TRAVIS_JOB_NUMBER SAUCE_BUILD=$TRAVIS_BUILD_NUMBER npm run test@sauce
