language: php

php:
  - 5.5
  - 5.6

addons:
  postgresql: "9.4"

install:
  - php -v
  - psql --version
  - node -v
  - npm version
  - composer install
  # - npm install bower
  # - ./node_modules/.bin/bower install

before_script:
  - cp .env.testing .env
  - vendor/bin/codecept build
  - psql -c 'CREATE DATABASE ub_baser_test;' -U postgres
  - php artisan --database=pgsql_test --seed migrate
  - php artisan db:dump --database pgsql_test

script:
  - vendor/bin/codecept run functional --steps  # --debug
