prod:
  hosts:
    ub-baser.uio.no:
  # vars:
  #   ansible_user: deploy
  #   ansible_ssh_private_key_file: ~/.ssh/id_rsa.ub-baser-deploy

dev:
  hosts:
    ubprod01-bas-utv.uio.no:
  # vars:
  #  ansible_ssh_common_args = '-F /dev/null'
  #   ansible_user: deploy
  #   ansible_ssh_private_key_file: ~/.ssh/id_rsa.ub-baser-deploy-dev
