version: '3'

volumes:
  storage:

services:

  app:
    image: ub-baser:latest
    logging:
      driver: journald
      options:
        tag: ub-baser
    environment:
      - APP_VERSION
      - APP_ENV=production
      - APP_DEBUG=false
    env_file:
      - ../../.env
    ports:
      - 80:80
      - 443:443
    volumes:
      - storage:/app/storage
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 20
