version: '3'

volumes:
  storage:
  pgdata_staging:

services:

  db:
    build: ../postgres
    volumes:
      - pgdata_staging:/var/lib/postgresql/data
    container_name: ub-baser-db-staging
    environment:
      - POSTGRES_USER=ub-baser-staging
      - POSTGRES_PASSWORD=ub-baser-staging
      - POSTGRES_INITDB_ARGS=--no-locale --encoding=UTF8

  app:
    image: ub-baser:latest
    build:
      context: ../..
      dockerfile: docker/Dockerfile
      args:
        - GITHUB_TOKEN
    container_name: ub-baser-app-staging
    environment:
      - APP_ENV=staging
      - APP_DEBUG=true
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=ub-baser-staging
      - POSTGRES_USER=ub-baser-staging
      - POSTGRES_PASSWORD=ub-baser-staging
      - APP_KEY=DoesNotNeedToBeRandomInDevEnviro
    ports:
      - 8081:80
    volumes:
      - ../..:/app/
      - storage:/app/storage
      #- ../../storage:/app/storage
    depends_on:
      - db
