version: '3'

volumes:
  storage:
  pgdata_testing:

services:

  db:
    build: ../postgres
    volumes:
      - pgdata_testing:/var/lib/postgresql/data
    container_name: ub-baser-db-testing
    environment:
      - DB_DATABASE=ub-baser-test
      - DB_USERNAME=ub-baser-test
      - DB_PASSWORD=ub-baser-test

  app:
    image: ub-baser:latest
    build:
      context: ../..
      dockerfile: docker/Dockerfile
      args:
        - GITHUB_TOKEN
    environment:
      - APP_ENV=testing
      - APP_DEBUG=true
      - DB_CONNECTION=pgsql
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DATABASE=ub-baser-test
      - DB_USERNAME=ub-baser-test
      - DB_PASSWORD=ub-baser-test
      - APP_KEY=DoesNotNeedToBeRandomInDevEnviro
    ports:
      - 8080:80
    container_name: ub-baser-app-testing
    volumes:
      - ../..:/app/
      - storage:/app/storage
      #- ../../storage:/app/storage
    depends_on:
      - db
