---
- name: Check if we have host key
  shell:
    cmd: grep 'github.com' ~/.ssh/known_hosts
  register: result
  changed_when: result.rc == 1
  notify:
    - Add host key

- name: Git pull
  git:
    repo: git@github.com:scriptotek/ub-baser.git
    dest: /data/ub-baser
    version: deploy

- name: Build
  shell:
    chdir: /data/ub-baser
    cmd: ./build.sh

- name: Deploy
  args:
    chdir: /data/ub-baser
  shell: |
    APP_VERSION=$(git rev-parse HEAD) docker stack deploy --compose-file docker/compose/production.yml ub-baser
    docker service update --force ub-baser_app

- name: Wait for site to come up
  uri:
    url: "https://ub-baser.uio.no/"
  register: result
  until: result.status == 200
  retries: 60
  delay: 1
